- name: check are raw images created
  local_action: |
    shell ls /var/lib/libvirt/images/gluster-{{ inventory_hostname}}.img
  register: ls_results
  changed_when: false
  failed_when: false

- name: create raw images for docker storage
  local_action: |
    shell qemu-img create -f raw /var/lib/libvirt/images/gluster-{{ inventory_hostname}}.img 500G
  when: ls_results.rc > 0

- name: check is gluster already attached
  local_action: |
    shell virsh dumpxml {{inventory_hostname}} | grep -q 'gluster-{{inventory_hostname}}'
  register: disk_attached
  changed_when: false
  failed_when: false

- name: add new disk for gluster as vdc
  local_action: |
    shell virsh attach-disk {{inventory_hostname}} --source /var/lib/libvirt/images/gluster-{{inventory_hostname}}.img --persistent --target vdc
  when: disk_attached.rc > 0
